# Generated by Django 5.0.1 on 2024-04-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate_alter_orders_email_alter_orders_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rent_price',
            field=models.IntegerField(default=0),
        ),
    ]
