# Generated by Django 5.0.1 on 2024-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rentinfo_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinfo',
            name='extra_info_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
