# Generated by Django 5.0.6 on 2024-06-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_product_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
