# Generated by Django 5.0.6 on 2024-06-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_qty',
        ),
    ]
