# Generated by Django 5.0.6 on 2024-06-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_product_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='update_desc',
        ),
    ]
