# Generated by Django 5.0.6 on 2024-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_orderupdate_update_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
    ]
