# Generated by Django 5.0.6 on 2024-06-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orderupdate_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeProduct',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=50)),
                ('theme_category', models.CharField(default='', max_length=50)),
                ('theme_rent_price', models.IntegerField(default=0)),
                ('theme_price', models.IntegerField(default=0)),
                ('theme_pub_date', models.DateField()),
                ('theme_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
