# Generated by Django 5.0.6 on 2024-06-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_themeproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themeproduct',
            old_name='theme_id',
            new_name='theme_product_id',
        ),
        migrations.RenameField(
            model_name='themeproduct',
            old_name='theme_name',
            new_name='theme_product_name',
        ),
    ]
