# Generated by Django 5.0.6 on 2024-06-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rename_theme_id_themeproduct_theme_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('product_type', models.CharField(choices=[('product', 'Product'), ('theme_product', 'ThemeProduct')], max_length=15)),
            ],
        ),
    ]
