# Generated by Django 5.0.6 on 2024-06-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default=2, max_length=5000),
            preserve_default=False,
        ),
    ]
