# Generated by Django 5.0.6 on 2024-06-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_orderhistory_extra_info_alter_orderhistory_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHistory',
        ),
        migrations.AddField(
            model_name='signup',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='firstname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='phone_no',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='signup',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
